apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cyanweb-nginx
  name: cyanweb-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyanweb-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cyanweb-nginx
    spec:
      containers:
      - image: ghcr.io/usepa/cyanweb-nginx:dev-kube
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: cyanweb-config
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
      restartPolicy: Always
