apiVersion: v1
kind: Service
metadata:
  name: cyanweb-nginx
spec:
  type: NodePort
  selector:
    app: cyanweb-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
      name: http
#    - protocol: TCP
#      port: 7777
#      targetPort: 7777
#      name: flask
#    - protocol: TCP
#      port: 7778
#      targetPort: 7778
#      name: flask-waterbody