apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cyanweb-redis
  name: cyanweb-redis
  namespace: qed-45-stg
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    eks.amazonaws.com/compute-type: fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyanweb-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cyanweb-redis
    spec:
      containers:
      - image: registry.epa.gov/qed/cyanweb_kube/cyanweb-redis:dev-gl
        imagePullPolicy: Always
      # - image: cyan-redis
      #   imagePullPolicy: Never
        name: cyanweb-redis
        livenessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        ports:
          - containerPort: 6379
            protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: glcr-auth
