apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cyanweb-flask
  name: cyanweb-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyanweb-flask
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cyanweb-flask
    spec:
      containers:
      - image: ghcr.io/usepa/cyanweb-api:dev-kube
      # - image: cyanweb-api-testing
        imagePullPolicy: Always
        # imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: cyanweb-config
        name: cyanweb-flask
        ports:
        - containerPort: 5001
          protocol: TCP
        volumeMounts:
          - mountPath: /config
            name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: config-volume
          hostPath:
            path: /run/desktop/mnt/host/c/Users/inick/GitHub/cyanweb_kube/EPA-Cyano-Web/config
