apiVersion: v1
kind: ConfigMap
metadata:
  name: cyanweb-config
  namespace: qed-45-stg
  labels:
    app: cyanweb-config
data:
  APP_NAME: ${APP_NAME}
  CYANWEB_CRYPT_KEY: ${CYANWEB_CRYPT_KEY}
  DB_HOST: ${DB_HOST}
  DB_NAME: ${DB_NAME}
  DB_PASS: ${DB_PASS}
  DB_PORT: ${DB_PORT}
  # DB_ROOT_PASS: ${DB_ROOT_PASS}
  # DB_USER: ${DB_USER}
  # EMAIL: ${EMAIL}
  # EMAIL_FROM: ${EMAIL_FROM}
  # # EMAIL_PASS: ${EMAIL_PASS:-''}
  # EMAIL_PORT: ${EMAIL_PORT}
  # EMAIL_SMTP: ${EMAIL_SMTP}
  # FLASK_HOST: ${FLASK_HOST}
  # FLASK_PORT: ${FLASK_PORT}
  # HOST_DOMAIN: ${HOST_DOMAIN}
  # REDIS_HOSTNAME: ${REDIS_HOSTNAME}
  # REDIS_PORT: ${REDIS_PORT}
  # SESSION_EXPIRE_SECONDS: ${SESSION_EXPIRE_SECONDS}
  # SK: ${SK}
  # TOMCAT_API: ${TOMCAT_API}
  # WATERBODY_URL: ${WATERBODY_URL}