apiVersion: v1
kind: Service
metadata:
  name: cyanweb-nginx
  namespace: qed-kube-dev
spec:
  type: NodePort
  selector:
    app: cyanweb-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
