apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cyanweb-nginx
  name: cyanweb-nginx
  namespace: qed-45-stg
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    eks.amazonaws.com/compute-type: fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyanweb-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cyanweb-nginx
    spec:
      containers:
      - image: registry.epa.gov/qed/cyanweb_kube/cyanweb-nginx:dev-gl
        imagePullPolicy: Always
      # - image: cyan-webserver
      #   imagePullPolicy: Never
        name: nginx
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        - containerPort: 443
      restartPolicy: Always
