apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cyanweb-nginx
  name: cyanweb-nginx
  namespace: qed-kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyanweb-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cyanweb-nginx
    spec:
      containers:
      - image: ghcr.io/usepa/cyanweb-nginx:dev-kube
        imagePullPolicy: Always
      # - image: cyanweb-nginx-testing
      #   imagePullPolicy: Never
        name: nginx
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        - containerPort: 443
      restartPolicy: Always
