apiVersion: v1
kind: Service
metadata:
  name: cyanweb-nginx
  namespace: qed-45-stg
spec:
  # type: NodePort
  type: ClusterIP
  selector:
    app: cyanweb-nginx
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: http
      # nodePort: 30001
