apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: cyanweb-mysql
  name: cyanweb-mysql
  namespace: ${KUBECTL_NAMESPACE}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: cyanweb-mysql
  serviceName: cyanweb-mysql
  template:
    metadata:
      labels:
        app: cyanweb-mysql
    spec:
      containers:
      - image: registry.epa.gov/qed/cyanweb_kube/cyanweb-db:dev-gl
        imagePullPolicy: Always
      # - image: cyan-db
      #   imagePullPolicy: Never
        name: cyanweb-mysql
        env:
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "yes"
        readinessProbe:
          exec:
            command:
            - ls
            - /
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - ls
            - /
          initialDelaySeconds: 15
          periodSeconds: 30
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: cyanweb-mysql-pvolume
        ports:
        - containerPort: 3306
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      imagePullSecrets:
        - name: glcr-auth
      volumes:
      - name: cyanweb-mysql-pvolume
        persistentVolumeClaim:
          claimName: cyanweb-mysql-pvolume-claim1
