apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cyanweb-celery
  name: cyanweb-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyanweb-celery
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cyanweb-celery
    spec:
      containers:
      - args:
          - celery
          - -A
          - celery_worker.celery
          - worker
          - --loglevel=INFO
          - -c
          - '1'
        envFrom:
        - configMapRef:
            name: cyanweb-config
        image: ghcr.io/usepa/cyanweb-api:dev-kube
        # image: cyanweb-api-testing
        imagePullPolicy: Always
        # imagePullPolicy: Never
        name: cyanweb-flask
        volumeMounts:
          - mountPath: /config
            name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: config-volume
          hostPath:
            path: /run/desktop/mnt/host/c/Users/inick/GitHub/cyanweb_kube/EPA-Cyano-Web/config
