apiVersion: v1
kind: Service
metadata:
  name: cyanweb-flask
  namespace: cyanweb-kube
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: cyanweb-flask
  type: ClusterIP