apiVersion: v1
kind: ConfigMap
metadata:
  name: cyanweb-config
  labels:
    app: cyanweb-config
data:
  DB_HOST: "cyanweb-db"
  DB_NAME: "cyan_web_app_db"
  DB_PORT: "3306"
  DB_USER: "cyano"
  EMAIL: "cyanomailserver@gmail.com"
  EMAIL_PORT: "465"
  EMAIL_SMTP: "smtp.gmail.com"
  ENV_NAME: "dev-kube"
  FLASK_HOST: "cyanweb-api"
  FLASK_PORT: "5001"
  HOST_DOMAIN: "http://localhost"
  HOSTNAME: "docker"
  DOCKER_HOSTNAME: "kubernetes"
  REDIS_HOSTNAME: "cyanweb-redis"
  REDIS_PORT: "6379"
  SESSION_EXPIRE_SECONDS: "1200"
  TOMCAT_API: "https://cyan.epa.gov"
  WATERBODY_URL: ""