# # Cyanweb Config PV
##############################################################################
# # NOTE: Will not need this PV, using "echo $VAL > /path/to/file.txt" method
##############################################################################
# # ---
# # apiVersion: v1
# # kind: PersistentVolume
# # metadata:
# #   name: cyanweb-config-pv
# #   namespace: qed-45-stg
# #   labels:
# #     type: local
# # spec:
# #   storageClassName: cyanweb-config-pv
# #   accessModes:
# #     - ReadWriteMany
# #   capacity:
# #     storage: 1Gi
# #   hostPath:
# #     path: /run/desktop/mnt/host/c/Users/inick/GitHub/cyanweb_kube/EPA-Cyano-Web/config
# # ---
##############################################################################

# # Cyanweb MySQL PV
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: cyanweb-mysql-pv
#   namespace: qed-45-stg
#   labels:
#     type: local
# spec:
#   storageClassName: cyanweb-mysql-pv
#   accessModes:
#     - ReadWriteMany
#   capacity:
#     storage: 5Gi
#   hostPath:
#     path: /run/desktop/mnt/host/c/Users/inick/mysql_data
# ---
