apiVersion: v1
kind: Service
metadata:
  name: cyanweb-redis
  namespace: ${KUBECTL_NAMESPACE}
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: cyanweb-redis
  type: ClusterIP