apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cyanweb-redis
  name: cyanweb-redis
  namespace: qed-kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyanweb-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cyanweb-redis
    spec:
      containers:
      - image: ghcr.io/usepa/cyanweb-redis:dev-kube
      # - image: redis:latest
      #   imagePullPolicy: Always
        name: cyanweb-redis
        livenessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        ports:
          - containerPort: 6379
            protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
